/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SoilRouteImport } from './routes/soil'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as ReportsLedgerRouteImport } from './routes/reports.ledger'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as AccountsTransactionsRouteImport } from './routes/accounts.transactions'
import { Route as AccountsSupplierDueRouteImport } from './routes/accounts.supplier-due'
import { Route as AccountsReceiveRouteImport } from './routes/accounts.receive'
import { Route as AccountsPaymentRouteImport } from './routes/accounts.payment'
import { Route as AccountsListRouteImport } from './routes/accounts.list'
import { Route as AccountsIncomeRouteImport } from './routes/accounts.income'
import { Route as AccountsExpenseRouteImport } from './routes/accounts.expense'
import { Route as AccountsCustomerDueRouteImport } from './routes/accounts.customer-due'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilRoute = SoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const ReportsLedgerRoute = ReportsLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => ReportsRoute,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsTransactionsRoute = AccountsTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsSupplierDueRoute = AccountsSupplierDueRouteImport.update({
  id: '/supplier-due',
  path: '/supplier-due',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsReceiveRoute = AccountsReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsPaymentRoute = AccountsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsListRoute = AccountsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsIncomeRoute = AccountsIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsExpenseRoute = AccountsExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsCustomerDueRoute = AccountsCustomerDueRouteImport.update({
  id: '/customer-due',
  path: '/customer-due',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/expenses': typeof ExpensesRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/salary': typeof SalaryRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/soil': typeof SoilRoute
  '/stock': typeof StockRoute
  '/accounts/customer-due': typeof AccountsCustomerDueRoute
  '/accounts/expense': typeof AccountsExpenseRoute
  '/accounts/income': typeof AccountsIncomeRoute
  '/accounts/list': typeof AccountsListRoute
  '/accounts/payment': typeof AccountsPaymentRoute
  '/accounts/receive': typeof AccountsReceiveRoute
  '/accounts/supplier-due': typeof AccountsSupplierDueRoute
  '/accounts/transactions': typeof AccountsTransactionsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/accounts/': typeof AccountsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/expenses': typeof ExpensesRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/salary': typeof SalaryRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/soil': typeof SoilRoute
  '/stock': typeof StockRoute
  '/accounts/customer-due': typeof AccountsCustomerDueRoute
  '/accounts/expense': typeof AccountsExpenseRoute
  '/accounts/income': typeof AccountsIncomeRoute
  '/accounts/list': typeof AccountsListRoute
  '/accounts/payment': typeof AccountsPaymentRoute
  '/accounts/receive': typeof AccountsReceiveRoute
  '/accounts/supplier-due': typeof AccountsSupplierDueRoute
  '/accounts/transactions': typeof AccountsTransactionsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/accounts': typeof AccountsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/expenses': typeof ExpensesRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/salary': typeof SalaryRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/soil': typeof SoilRoute
  '/stock': typeof StockRoute
  '/accounts/customer-due': typeof AccountsCustomerDueRoute
  '/accounts/expense': typeof AccountsExpenseRoute
  '/accounts/income': typeof AccountsIncomeRoute
  '/accounts/list': typeof AccountsListRoute
  '/accounts/payment': typeof AccountsPaymentRoute
  '/accounts/receive': typeof AccountsReceiveRoute
  '/accounts/supplier-due': typeof AccountsSupplierDueRoute
  '/accounts/transactions': typeof AccountsTransactionsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/reports/ledger': typeof ReportsLedgerRoute
  '/accounts/': typeof AccountsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/delivery'
    | '/expenses'
    | '/labor'
    | '/login'
    | '/production'
    | '/salary'
    | '/settings'
    | '/sms'
    | '/soil'
    | '/stock'
    | '/accounts/customer-due'
    | '/accounts/expense'
    | '/accounts/income'
    | '/accounts/list'
    | '/accounts/payment'
    | '/accounts/receive'
    | '/accounts/supplier-due'
    | '/accounts/transactions'
    | '/orders/$orderId'
    | '/orders/new'
    | '/reports/ledger'
    | '/accounts/'
    | '/orders/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delivery'
    | '/expenses'
    | '/labor'
    | '/login'
    | '/production'
    | '/salary'
    | '/settings'
    | '/sms'
    | '/soil'
    | '/stock'
    | '/accounts/customer-due'
    | '/accounts/expense'
    | '/accounts/income'
    | '/accounts/list'
    | '/accounts/payment'
    | '/accounts/receive'
    | '/accounts/supplier-due'
    | '/accounts/transactions'
    | '/orders/$orderId'
    | '/orders/new'
    | '/reports/ledger'
    | '/accounts'
    | '/orders'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/delivery'
    | '/expenses'
    | '/labor'
    | '/login'
    | '/production'
    | '/salary'
    | '/settings'
    | '/sms'
    | '/soil'
    | '/stock'
    | '/accounts/customer-due'
    | '/accounts/expense'
    | '/accounts/income'
    | '/accounts/list'
    | '/accounts/payment'
    | '/accounts/receive'
    | '/accounts/supplier-due'
    | '/accounts/transactions'
    | '/orders/$orderId'
    | '/orders/new'
    | '/reports/ledger'
    | '/accounts/'
    | '/orders/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  DeliveryRoute: typeof DeliveryRoute
  ExpensesRoute: typeof ExpensesRoute
  LaborRoute: typeof LaborRoute
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRoute
  SalaryRoute: typeof SalaryRoute
  SettingsRoute: typeof SettingsRoute
  SmsRoute: typeof SmsRoute
  SoilRoute: typeof SoilRoute
  StockRoute: typeof StockRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil': {
      id: '/soil'
      path: '/soil'
      fullPath: '/soil'
      preLoaderRoute: typeof SoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/reports/ledger': {
      id: '/reports/ledger'
      path: '/ledger'
      fullPath: '/reports/ledger'
      preLoaderRoute: typeof ReportsLedgerRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/transactions': {
      id: '/accounts/transactions'
      path: '/transactions'
      fullPath: '/accounts/transactions'
      preLoaderRoute: typeof AccountsTransactionsRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/supplier-due': {
      id: '/accounts/supplier-due'
      path: '/supplier-due'
      fullPath: '/accounts/supplier-due'
      preLoaderRoute: typeof AccountsSupplierDueRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/receive': {
      id: '/accounts/receive'
      path: '/receive'
      fullPath: '/accounts/receive'
      preLoaderRoute: typeof AccountsReceiveRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/payment': {
      id: '/accounts/payment'
      path: '/payment'
      fullPath: '/accounts/payment'
      preLoaderRoute: typeof AccountsPaymentRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/list': {
      id: '/accounts/list'
      path: '/list'
      fullPath: '/accounts/list'
      preLoaderRoute: typeof AccountsListRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/income': {
      id: '/accounts/income'
      path: '/income'
      fullPath: '/accounts/income'
      preLoaderRoute: typeof AccountsIncomeRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/expense': {
      id: '/accounts/expense'
      path: '/expense'
      fullPath: '/accounts/expense'
      preLoaderRoute: typeof AccountsExpenseRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/customer-due': {
      id: '/accounts/customer-due'
      path: '/customer-due'
      fullPath: '/accounts/customer-due'
      preLoaderRoute: typeof AccountsCustomerDueRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsCustomerDueRoute: typeof AccountsCustomerDueRoute
  AccountsExpenseRoute: typeof AccountsExpenseRoute
  AccountsIncomeRoute: typeof AccountsIncomeRoute
  AccountsListRoute: typeof AccountsListRoute
  AccountsPaymentRoute: typeof AccountsPaymentRoute
  AccountsReceiveRoute: typeof AccountsReceiveRoute
  AccountsSupplierDueRoute: typeof AccountsSupplierDueRoute
  AccountsTransactionsRoute: typeof AccountsTransactionsRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsCustomerDueRoute: AccountsCustomerDueRoute,
  AccountsExpenseRoute: AccountsExpenseRoute,
  AccountsIncomeRoute: AccountsIncomeRoute,
  AccountsListRoute: AccountsListRoute,
  AccountsPaymentRoute: AccountsPaymentRoute,
  AccountsReceiveRoute: AccountsReceiveRoute,
  AccountsSupplierDueRoute: AccountsSupplierDueRoute,
  AccountsTransactionsRoute: AccountsTransactionsRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  DeliveryRoute: DeliveryRoute,
  ExpensesRoute: ExpensesRoute,
  LaborRoute: LaborRoute,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRoute,
  SalaryRoute: SalaryRoute,
  SettingsRoute: SettingsRoute,
  SmsRoute: SmsRoute,
  SoilRoute: SoilRoute,
  StockRoute: StockRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
